default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: new_password
  host: localhost

development:
  <<: *default
  database: quakeFetchData

test:
  <<: *default
  database: your_project_test

production:
  <<: *default
  database: your_project_production
  password: <%= ENV['YOUR_PROJECT_DATABASE_PASSWORD'] %>
  host: <%= ENV['YOUR_PROJECT_DATABASE_HOST'] %>
